config/routes.rb
Rails.application.routes.draw do
  resources :leagues, only: [:show]
  resources :teams, only: [:show]
  root 'leagues#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  REDIS = Redis.new()
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_redis, only: [:index, :show]
  before_action :set_leagues, only: [:index, :show]

  def index
  end

  def show
    @league_name = params[:name]
    @id = params[:id]
    url_teams = URI("https://v3.football.api-sports.io/teams?league=#{@id}&season=2023")
    url_matches = URI("https://v3.football.api-sports.io/fixtures?status=NS&league=#{@id}&season=2023")

    if !REDIS.exists?("teams-#{@id}")
      teams = get_data(url_teams).read_body
      REDIS.set("teams-#{@id}", teams)
    end

    if !REDIS.exists?("matches-#{@id}")
      matches = get_data(url_matches).read_body
      REDIS.set("matches-#{@id}", matches)
    end
    @teams = JSON.parse(REDIS.get("teams-#{@id}"))['response']
    @matches = JSON.parse(REDIS.get("matches-#{@id}"))['response']
  end

  private

  def set_redis
    REDIS.select(1)
  end

  def set_leagues
    @leagues = JSON.parse(REDIS.get('leagues'))['response']
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_redis, only: [:show]

  def show
    @team_id = params[:team_id]
    @team_name = params[:team_name]

    url_team = URI("https://v3.football.api-sports.io/teams?id=#{@team_id}")
    url_players = URI("https://v3.football.api-sports.io/players/squads?team=#{@team_id}")

    if !REDIS.exists?("team-#{@team_id}")
      team = get_data(url_team).read_body
      REDIS.set("team-#{@team_id}", team)
    end

    if !REDIS.exists?("players-#{@team_id}")
      players = get_data(url_players).read_body
      REDIS.set("players-#{@team_id}", players)
    end

    @team = JSON.parse(REDIS.get("team-#{@team_id}"))['response']
    @players = JSON.parse(REDIS.get("players-#{@team_id}"))['response']
  end

  private

  def set_redis
    REDIS.select(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchInfo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leagues/index.html.erb
<h1 style='text-align: center; font-size: 7em;'>Leagues</h1>

<div style='display: grid; grid-template-columns: repeat(auto-fill,minmax(20rem, 1fr));'>
  <% @leagues.each do |league| %>
    <div>
      <%= link_to league['league']['name'], league_path(id: league['league']['id'], name: league['league']['name']), style:'text-decoration: none; color: black;' %>
    </div>
  <% end %>
</div>

app/views/leagues/show.html.erb
<h1 style='text-align: center; font-size: 7em;'><%= @league_name %></h1>
<div style='display: flex; justify-content: center; gap: 5rem;'>
  <div>
    <h1 style='text-align: center;'>Teams</h1>
    <% @teams.each do |team| %>
      <div style='text-align: center;'>
        <%= link_to "#{team['team']['name']}", team_path(team_id: team['team']['id'], team_name: team['team']['name']), style:'text-decoration: none; font-size: 1.5em; color: black;' %>
      </div>
    <% end %>
  </div>

  <div>
    <h1 style='text-align: center;'>Matches</h1>
    <div>
      <% @matches.first(10).each do |match| %>
        <div style='padding: .5rem; text-align: center'>
          <div style='font-size: 1.2em;'>
            <%= match['teams']['home']['name'] %>
            -
            <%= match['teams']['away']['name'] %>
          </div>
          <div>
            <%= Date.parse(match['fixture']['date']).strftime('%d %B %Y') %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>